version: '3.8'

services:
  web:
    # Build Nginx image, map container port 8334 to host port 8081
    build: .
    ports:
      - "8081:8334"
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  app:
    # Build Python image (polybot directory)
    build: ./polybot
    expose:
      - "8443"
    volumes:
      - ./:/app
