version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"

  nginx:
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    ports:
      - "8334:8334"
