version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"

  nginx:
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    ports:
      - "50:50"
