version: '3.8'

services:
  app:
    # Build the Docker image using the current directory as the build context
    build:
      context: .
      dockerfile: Dockerfile
    # Expose the port that the app will run on
    expose:
      - "8443"
    # Mount the current directory to /app inside the container
    volumes:
      - ./:/app
    env_file:
      - .env


  web:
    # Build the Docker image from the Nginx directory
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    # Expose the port that Nginx will run on and map it to the host port 8081
    ports:
      - "8081:8334"
    # Mount the Nginx configuration file
    volumes:
      - ./Nginx/Nginx.conf:/etc/nginx/nginx.conf:ro
